# Generated by Django 5.0.6 on 2026-05-06 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commentlike_commentlike_unique_user_comment_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('parent_id', models.F('id')), _negated=True), name='comment_parent_not_self'),
        ),
    ]
