# Generated by Django 5.0.6 on 2026-06-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_comment_parent_not_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
